"""add media table

Revision ID: 450a490afc80
Revises: 8ad19108e114
Create Date: 2022-11-27 09:17:32.097606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '450a490afc80'
down_revision = '8ad19108e114'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('news_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_guid'], ['news.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_media_guid'), 'media', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_guid'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
